# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      # - source: .github/workflows/
     #   dest: .github/workflows/
     #   deleteOrphaned: true
     #   exclude: |
     #     send-updates.yml
     #     test-send-updates.yml
     #     starting-course.yml
     #     release-notes.yml
      - source: .github/workflows/delete-preview.yml
        dest: .github/workflows/delete-preview.yml
      - source: .github/workflows/render-all.yml
        dest: .github/workflows/render-site.yml
      - source: .github/workflows/pull_request.yml
        dest: .github/workflows/pull_request.yml
      - source: config_automation.yml
        dest: config_automation.yml
      - source: .github/workflows/check-url.yml
        dest: .github/workflows/check-url.yml
      - source: .github/workflows/docker-test.yml
        dest: .github/workflows/docker-test.yml
      - source: config_automation.yml
        dest: config_automation.yml
  # Repositories to receive changes
    repos: |
      ottrproject/ottrproject.org
      jhudsl/Baltimore_Community_Course
      maculatus/test-ottr-website
      dr-sayyadhury/OTTR_Template_Website_repo
      whalera1901/Current-projects
      GenetcXBiotech1/Dr.Fierst_lab
      buriedsand/glbio-personal-website
      PurplFeesh/test-ottr-site
      jcha40/ottr_test_site
      jhudsl/ITN_computing_resources
      fhdsl/ITN_course_search
      cansavvy/cansavvy_website
      ottrproject/metricminer-dashboard
      ottrproject/metricminer.org
      fhdsl/Intermediate_R
      fhdsl/AnVIL_Poll_2024
      fhdsl/ITN_Workshops_2024
      fhdsl/containers-for-scientists-sandbox
      fhdsl/nyu2024-galaxy-activity
      fhdsl/OPEN_Survey_2024
      fhdsl/DaSL_Collection
      fhdsl/Moffitt_ITN_Workshop
      fhdsl/UMich_ITN_Workshop
      fhdsl/ITN_Workshops_2025
      fhdsl/itn-training-metrics
      fhsdsl/daseh_instructor_guide

###ADD NEW REPO HERE following the format above#

### These are custom groups for syncing -- not all files needs to be synced # will update later
  - files:
      - source: .github/workflows/delete-preview.yml
        dest: .github/workflows/delete-preview.yml
      - source: .github/workflows/render-all.yml
        dest: .github/workflows/render-site.yml
      - source: .github/workflows/pull_request.yml
        dest: .github/workflows/pull_request.yml
      - source: config_automation.yml
        dest: config_automation.yml
      - source: .github/workflows/check-url.yml
        dest: .github/workflows/check-url.yml
      - source: .github/workflows/docker-test.yml
        dest: .github/workflows/docker-test.yml
      - source: config_automation.yml
        dest: config_automation.yml
      - source: resources/
        dest: resources

    repos: |
      opencasestudies/ocs-ripples-ancestry
      opencasestudies/ocs-bp-template
      opencasestudies/ocs-template
      
      
      
